# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
import numpy
import numpy.typing
import typing
__all__ = [
    "AprilGrid",
    "BoardEstimateResult",
    "BoardEstimator",
    "CameraIntrinsics",
    "CharucoBoard",
    "CharucoEstimateResult",
    "CharucoRefiner",
    "CharucoTelemetryResult",
    "CornerRefinementMode",
    "DetectionResult",
    "Detector",
    "DistortionModel",
    "EdLinesImbalanceGatePolicy",
    "PipelineTelemetryResult",
    "PyPose",
    "QuadExtractionMode",
    "SegmentationConnectivity",
    "TagFamily",
    "ThresholdMode",
    "init_tracy",
]

@typing.final
class AprilGrid:
    r"""
    Configuration for an AprilGrid board.
    
    Every grid cell contains one marker; tag IDs are assigned in row-major order.
    
    The `family` parameter is checked against the board marker count at
    construction time: if the board needs more tag IDs than the dictionary
    provides, a `ValueError` is raised.
    """
    @property
    def rows(self) -> builtins.int:
        r"""
        Number of marker rows.
        """
    @property
    def cols(self) -> builtins.int:
        r"""
        Number of marker columns.
        """
    def __new__(cls, rows: builtins.int, cols: builtins.int, spacing: builtins.float, marker_length: builtins.float, family: TagFamily) -> AprilGrid:
        r"""
        Create an AprilGrid board configuration.
        
        - `rows` / `cols`: number of markers in each dimension.
        - `spacing`: gap between adjacent markers (metres).
        - `marker_length`: physical side length of one marker (metres).
        - `family`: tag family used on this board (determines max valid ID).
        """

@typing.final
class BoardEstimateResult:
    r"""
    Typed result returned by `BoardEstimator.estimate` (Python).
    """
    @property
    def ids(self) -> numpy.typing.NDArray[numpy.int32]: ...
    @property
    def corners(self) -> numpy.typing.NDArray[numpy.float32]: ...
    @property
    def board_pose(self) -> typing.Optional[numpy.typing.NDArray[numpy.float64]]: ...
    @property
    def board_cov(self) -> typing.Optional[numpy.typing.NDArray[numpy.float64]]: ...

@typing.final
class BoardEstimator:
    r"""
    Estimator for multi-tag board poses (AprilGrid).
    
    Uses the decoded tags as geometric priors to estimate the camera-to-board
    transform via LO-RANSAC + Anisotropic Weighted Levenberg–Marquardt.
    
    Reuse a single `BoardEstimator` across frames to amortise the one-time
    scratch-buffer allocation.
    """
    def __new__(cls, board: AprilGrid) -> BoardEstimator:
        r"""
        Create a `BoardEstimator` for the given board.
        
        Reuse the same estimator across frames to avoid re-allocating scratch buffers.
        """
    @classmethod
    def from_charuco(cls, board: CharucoBoard) -> BoardEstimator:
        r"""
        Create a `BoardEstimator` for a ChAruco board.
        
        This uses the ArUco tags for board pose estimation without refining saddle points.
        """
    def estimate(self, detector: Detector, img: numpy.typing.NDArray[numpy.uint8], intrinsics: CameraIntrinsics) -> BoardEstimateResult:
        r"""
        Run the board pose estimation pipeline on a single frame.
        
        Calls the standard tag detector internally, then solves for the board
        pose using all detected markers.
        
        Returns a [`BoardEstimateResult`] with fields:
        - `ids`:         `(N,) int32`  — decoded ArUco IDs
        - `corners`:     `(N, 4, 2) float32`  — tag corners
        - `board_pose`:  `(7,) float64` `[tx, ty, tz, qx, qy, qz, qw]` or `None`
        - `board_cov`:   `(6, 6) float64` **body-frame** se(3) pose covariance
          (ordered `[t, ω]`; see `docs/explanation/coordinates.md §5.1`), or `None` if no
          board was estimated **or** the LM Hessian was singular (the
          pose still ships as a best-effort estimate; only the calibrated
          uncertainty is unavailable).
        """

@typing.final
class CameraIntrinsics:
    r"""
    Camera intrinsic parameters with optional lens distortion.
    
    Construct with just `(fx, fy, cx, cy)` for a rectified camera, or
    pass `distortion_model` and `dist_coeffs` for a distorted camera:
    
    ```python
    # Pinhole (no distortion)
    k = CameraIntrinsics(fx=800.0, fy=800.0, cx=400.0, cy=300.0)
    
    # Brown-Conrady
    k = CameraIntrinsics(
        fx=800.0, fy=800.0, cx=400.0, cy=300.0,
        distortion_model=DistortionModel.BrownConrady,
        dist_coeffs=[-0.3, 0.1, 0.001, -0.002, 0.0],
    )
    
    # Kannala-Brandt fisheye
    k = CameraIntrinsics(
        fx=380.0, fy=380.0, cx=320.0, cy=240.0,
        distortion_model=DistortionModel.KannalaBrandt,
        dist_coeffs=[0.1, -0.01, 0.001, 0.0],
    )
    ```
    """
    @property
    def fx(self) -> builtins.float: ...
    @fx.setter
    def fx(self, value: builtins.float) -> None: ...
    @property
    def fy(self) -> builtins.float: ...
    @fy.setter
    def fy(self, value: builtins.float) -> None: ...
    @property
    def cx(self) -> builtins.float: ...
    @cx.setter
    def cx(self, value: builtins.float) -> None: ...
    @property
    def cy(self) -> builtins.float: ...
    @cy.setter
    def cy(self, value: builtins.float) -> None: ...
    @property
    def distortion_model(self) -> DistortionModel:
        r"""
        The distortion model to use. Defaults to [`DistortionModel::Pinhole`].
        """
    @distortion_model.setter
    def distortion_model(self, value: DistortionModel) -> None:
        r"""
        The distortion model to use. Defaults to [`DistortionModel::Pinhole`].
        """
    @property
    def dist_coeffs(self) -> builtins.list[builtins.float]:
        r"""
        Distortion coefficients corresponding to the chosen model.
        
        - `BrownConrady`: `[k1, k2, p1, p2, k3]` (5 values)
        - `KannalaBrandt`: `[k1, k2, k3, k4]` (4 values)
        - `Pinhole`: ignored (may be empty)
        """
    @dist_coeffs.setter
    def dist_coeffs(self, value: typing.Sequence[builtins.float]) -> None:
        r"""
        Distortion coefficients corresponding to the chosen model.
        
        - `BrownConrady`: `[k1, k2, p1, p2, k3]` (5 values)
        - `KannalaBrandt`: `[k1, k2, k3, k4]` (4 values)
        - `Pinhole`: ignored (may be empty)
        """
    def __new__(cls, fx: builtins.float, fy: builtins.float, cx: builtins.float, cy: builtins.float, distortion_model: DistortionModel = DistortionModel.Pinhole, dist_coeffs: typing.Optional[typing.Sequence[builtins.float]] = None) -> CameraIntrinsics: ...

@typing.final
class CharucoBoard:
    r"""
    Configuration for a ChAruco board.
    
    Markers occupy the checkerboard squares where `(row + col)` is even.
    The interior checkerboard corners (saddle points) are used for sub-pixel
    pose estimation.
    
    The `family` parameter is checked against the board marker count at
    construction time: if the board needs more tag IDs than the dictionary
    provides, a `ValueError` is raised.
    """
    @property
    def rows(self) -> builtins.int:
        r"""
        Number of square rows.
        """
    @property
    def cols(self) -> builtins.int:
        r"""
        Number of square columns.
        """
    def __new__(cls, rows: builtins.int, cols: builtins.int, square_length: builtins.float, marker_length: builtins.float, family: TagFamily) -> CharucoBoard:
        r"""
        Create a ChAruco board configuration.
        
        - `rows` / `cols`: number of checkerboard squares in each dimension.
        - `square_length`: physical side length of one square (metres).
        - `marker_length`: physical side length of one ArUco marker (metres).
        - `family`: tag family used on this board (determines max valid ID).
        """

@typing.final
class CharucoEstimateResult:
    r"""
    Typed result returned by `CharucoRefiner.estimate` (Python).
    """
    @property
    def ids(self) -> numpy.typing.NDArray[numpy.int32]: ...
    @property
    def corners(self) -> numpy.typing.NDArray[numpy.float32]: ...
    @property
    def saddle_ids(self) -> numpy.typing.NDArray[numpy.int32]: ...
    @property
    def saddle_pts(self) -> numpy.typing.NDArray[numpy.float32]: ...
    @property
    def saddle_obj(self) -> numpy.typing.NDArray[numpy.float64]: ...
    @property
    def board_pose(self) -> typing.Optional[numpy.typing.NDArray[numpy.float64]]: ...
    @property
    def board_cov(self) -> typing.Optional[numpy.typing.NDArray[numpy.float64]]: ...
    @property
    def telemetry(self) -> typing.Optional[CharucoTelemetryResult]: ...

@typing.final
class CharucoRefiner:
    r"""
    Extracts ChAruco saddle points from decoded ArUco detections and estimates
    the board pose via LO-RANSAC + Anisotropic Weighted Levenberg–Marquardt.
    
    Reuse a single `CharucoRefiner` across frames to amortise the one-time
    scratch-buffer allocation.
    """
    def __new__(cls, board: CharucoBoard) -> CharucoRefiner:
        r"""
        Create a `CharucoRefiner` for the given board.
        
        Reuse the same refiner across frames to avoid re-allocating scratch buffers.
        """
    def estimate(self, detector: Detector, img: numpy.typing.NDArray[numpy.uint8], intrinsics: CameraIntrinsics, debug_telemetry: builtins.bool = False) -> CharucoEstimateResult:
        r"""
        Run the full ChAruco pipeline on a single frame.
        
        Calls the standard ArUco tag detector internally, then extracts and
        refines saddle points, and estimates the board pose.
        
        Returns a dict with keys:
        - `ids`:         `(N,) int32`  — decoded ArUco IDs
        - `corners`:     `(N, 4, 2) float32`  — tag corners
        - `saddle_ids`:  `(S,) int32`  — accepted saddle-point indices
        - `saddle_pts`:  `(S, 2) float32`  — refined image coordinates
        - `saddle_obj`:  `(S, 3) float64`  — board-frame 3D coordinates
        - `board_pose`:  `(7,) float64` `[tx, ty, tz, qx, qy, qz, qw]` or `None`
        - `board_cov`:   `(6, 6) float64` **body-frame** se(3) pose covariance
          (ordered `[t, ω]`; see `docs/explanation/coordinates.md §5.1`), or `None` if no
          board was estimated **or** the LM Hessian was singular (the
          pose still ships as a best-effort estimate; only the calibrated
          uncertainty is unavailable).
        - `telemetry`:   dict with `"rejected_saddles"` `(R,2) float32`,
                         `"rejected_determinants"` `(R,) float32`, and
                         `"rejected_reasons"` `(R,) uint8` (0 =
                         `LowStructureTensorDet`, 1 = `SingularCovariance`)
                         or `None` (only populated when
                         `debug_telemetry=True`). Always gate
                         `rejected_determinants` aggregations on
                         `rejected_reasons` — the `SingularCovariance`
                         lane writes NaN into the determinants buffer.
        """

@typing.final
class CharucoTelemetryResult:
    r"""
    Telemetry from `CharucoRefiner.estimate` (Python), populated when `debug_telemetry=True`.
    """
    @property
    def rejected_saddles(self) -> numpy.typing.NDArray[numpy.float32]: ...
    @property
    def rejected_determinants(self) -> numpy.typing.NDArray[numpy.float32]:
        r"""
        Structure-tensor determinant for the low-det rejection lane.
        NaN for entries from the singular-covariance lane — always gate
        on [`Self::rejected_reasons`] before computing aggregates.
        """
    @property
    def rejected_reasons(self) -> numpy.typing.NDArray[numpy.uint8]:
        r"""
        Reason code for each rejected saddle (u8 repr of
        [`locus_core::charuco::RejectionReason`]: 0 =
        `LowStructureTensorDet`, 1 = `SingularCovariance`).
        """

@typing.final
class DetectionResult:
    r"""
    Typed result returned by `Detector.detect` (Python).
    """
    @property
    def ids(self) -> numpy.typing.NDArray[numpy.int32]: ...
    @property
    def corners(self) -> numpy.typing.NDArray[numpy.float32]: ...
    @property
    def error_rates(self) -> numpy.typing.NDArray[numpy.float32]: ...
    @property
    def poses(self) -> typing.Optional[numpy.typing.NDArray[numpy.float32]]: ...
    @property
    def rejected_corners(self) -> numpy.typing.NDArray[numpy.float32]: ...
    @property
    def rejected_error_rates(self) -> numpy.typing.NDArray[numpy.float32]: ...
    @property
    def rejected_funnel_status(self) -> numpy.typing.NDArray[numpy.uint8]:
        r"""
        Per-rejected-quad funnel status code (matches `locus.FunnelStatus`).
        Shape `(M,)` — same M as `rejected_corners`.
        """
    @property
    def telemetry(self) -> typing.Optional[PipelineTelemetryResult]: ...

@typing.final
class Detector:
    def detect(self, img: numpy.typing.NDArray[numpy.uint8], intrinsics: typing.Optional[CameraIntrinsics] = None, tag_size: typing.Optional[builtins.float] = None, debug_telemetry: builtins.bool = False) -> DetectionResult:
        r"""
        Detect tags and return a typed [`DetectionResult`] containing NumPy arrays.
        """
    def detect_concurrent(self, frames: typing.Sequence[numpy.typing.NDArray[numpy.uint8]], intrinsics: typing.Optional[CameraIntrinsics] = None, tag_size: typing.Optional[builtins.float] = None) -> builtins.list[DetectionResult]:
        r"""
        Detect tags in multiple frames concurrently using Rayon.
        
        Releases the Python GIL for the entire parallel section. The detector
        leases [`FrameContext`] objects from its internal pool; the pool size
        was set via `max_concurrent_frames` at construction time.
        
        Telemetry and rejected-corner data are not available via this method.
        """
    def config(self) -> builtins.str:
        r"""
        Returns the current detector configuration as a profile-JSON string.
        
        Python re-parses this into the Pydantic `DetectorConfig`, so the readback
        is total over every profile field (the former field-by-field FFI struct
        silently dropped knobs it did not re-copy).
        """
    def set_families(self, families: typing.Sequence[builtins.int]) -> None:
        r"""
        Update the tag families to be detected.
        """

@typing.final
class PipelineTelemetryResult:
    r"""
    Intermediate pipeline artifacts emitted when `debug_telemetry=True`.
    """
    @property
    def binarized(self) -> numpy.typing.NDArray[numpy.uint8]: ...
    @property
    def threshold_map(self) -> numpy.typing.NDArray[numpy.uint8]: ...
    @property
    def subpixel_jitter(self) -> typing.Optional[numpy.typing.NDArray[numpy.float32]]: ...
    @property
    def reprojection_errors(self) -> typing.Optional[numpy.typing.NDArray[numpy.float32]]: ...
    @property
    def routed_to(self) -> typing.Optional[numpy.typing.NDArray[numpy.uint8]]:
        r"""
        Per-candidate adaptive-router route labels (0 = low, 1 = high,
        255 = Static/not-routed). One entry per Phase-A candidate, populated
        only when `debug_telemetry=True` and `QuadExtractionPolicy::AdaptivePpb`
        is active for at least one candidate.
        """
    @property
    def ppb_estimate(self) -> typing.Optional[numpy.typing.NDArray[numpy.float32]]:
        r"""
        Per-candidate pixels-per-bit estimates (`bbox.short_side / min_outer_dim`).
        One entry per Phase-A candidate, populated only when `debug_telemetry=True`.
        """

@typing.final
class PyPose:
    @property
    def quaternion(self) -> builtins.list[builtins.float]: ...
    @property
    def translation(self) -> builtins.list[builtins.float]: ...

@typing.final
class CornerRefinementMode(enum.IntEnum):
    r"""
    Sub-pixel corner refinement applied during quad extraction.
    """
    None_ = ...  # runtime attribute is `None` (a Python keyword)
    r"""
    Keep the extractor's corners (EdLines' Gauss-Newton sub-pixel corners, or
    `ContourRdp`'s contour vertices). Required with `AdaptivePpb` routing.
    """
    Erf = ...
    r"""
    Fit each edge with a PSF-blurred step (ERF) model and intersect the edge lines.
    Incompatible with `EdLines` extraction.
    """

@typing.final
class DistortionModel(enum.IntEnum):
    r"""
    Identifies which lens distortion model the [`CameraIntrinsics`] coefficients apply to.
    """
    Pinhole = ...
    r"""
    Ideal pinhole camera — no distortion (pre-rectified image). Default.
    """
    BrownConrady = ...
    r"""
    Brown-Conrady polynomial radial + tangential distortion (OpenCV convention).
    
    `dist_coeffs` must contain exactly **5** values: `[k1, k2, p1, p2, k3]`.
    """
    KannalaBrandt = ...
    r"""
    Kannala-Brandt equidistant fisheye model.
    
    `dist_coeffs` must contain exactly **4** values: `[k1, k2, k3, k4]`.
    """

@typing.final
class EdLinesImbalanceGatePolicy(enum.IntEnum):
    r"""
    EdLines axis-to-diagonal imbalance gate: when the axis-aligned boundary partition is
    severely unbalanced (one arc above 40 % and another below 16 % of the boundary, the
    signature of two corners collapsing onto one extremal), re-partition along the diagonals.
    """
    Disabled = ...
    r"""
    Always keep the axis-aligned partition.
    """
    Enabled = ...
    r"""
    Divert severely unbalanced partitions to the diagonal partition.
    """

@typing.final
class QuadExtractionMode(enum.IntEnum):
    r"""
    Algorithm that turns a segmented component into a candidate quad.
    """
    ContourRdp = ...
    r"""
    Contour tracing, Douglas-Peucker simplification and reduction to four corners.
    """
    EdLines = ...
    r"""
    Edge drawing: boundary segmentation, robust line fits and a joint Gauss-Newton
    corner solve. Undistorted cameras only; pair with `CornerRefinementMode.None`.
    """

@typing.final
class SegmentationConnectivity(enum.IntEnum):
    r"""
    Pixel connectivity of the dark regions that segmentation groups into candidates.
    """
    Four = ...
    r"""
    4-connectivity: pixels connect horizontally and vertically only. Keeps dark squares
    that touch at a corner (checkerboards, AprilGrid connectors) apart.
    """
    Eight = ...
    r"""
    8-connectivity: pixels also connect diagonally. Joins borders thinner than a pixel on
    the diagonal, but fuses diagonally touching squares.
    """

@typing.final
class TagFamily(enum.IntEnum):
    r"""
    Fiducial marker dictionary to decode.
    """
    AprilTag16h5 = ...
    r"""
    AprilTag 16h5 (30 codes, 4x4 bits, minimum Hamming distance 5).
    """
    AprilTag36h11 = ...
    r"""
    AprilTag 36h11 (587 codes, 6x6 bits, minimum Hamming distance 11).
    """
    ArUco4x4_50 = ...
    r"""
    ArUco `DICT_4X4_50`.
    """
    ArUco4x4_100 = ...
    r"""
    ArUco `DICT_4X4_100`.
    """
    ArUco6x6_250 = ...
    r"""
    ArUco `DICT_6X6_250`.
    """
    ArUcoMip36h12 = ...
    r"""
    ArUco MIP 36h12 (250 codes, 6x6 bits; `DICT_ARUCO_MIP_36h12`).
    """

@typing.final
class ThresholdMode(enum.IntEnum):
    r"""
    How the per-pixel foreground threshold that feeds segmentation is built.
    """
    TileMidExtreme = ...
    r"""
    A fixed fraction (179/400 = 0.4475) of the min/max range over a 3x3 tile neighbourhood,
    below the midpoint the name records (every shipped profile).
    """
    LocalMean = ...
    r"""
    Per-pixel local mean over a `(2r+1)^2` window minus a noise-calibrated offset
    `clamp(round(noise_k * sigma_n), 2, 20)`. Opt-in.
    """

def _create_detector_from_config(config_json: builtins.str, decimation: typing.Optional[builtins.int] = None, threads: typing.Optional[builtins.int] = None, families: typing.Sequence[builtins.int] = [], max_concurrent_frames: typing.Optional[builtins.int] = None) -> Detector: ...

def _shipped_profile_json(name: builtins.str) -> builtins.str: ...

def init_tracy() -> None: ...

